version: "3.6"

services:
  # LDAP

  ldap:
    image: osixia/openldap
    environment:
      LDAP_ORGANISATION: "Meta"
      LDAP_ADMIN_PASSWORD: "admin"
    restart: always
    ports:
      - "389:389"
    volumes:
      - ./ldap/ldap_data:/var/lib/ldap
      - ./ldap/ldap_config:/etc/ldap/slapd.d

  phpldapadmin:
    image: osixia/phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: ldap
      PHPLDAPADMIN_HTTPS: "false"
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - ldap

  # GITLAB

  web-gitlab:
    image: "gitlab/gitlab-ee:latest"
    restart: unless-stopped
    hostname: "web-gitlab"
    ports:
      - "82:80"
      - "2443:443"
    volumes:
      - "./gitlab/config:/etc/gitlab"
      - "./gitlab/logs:/var/log/gitlab"
      - "./gitlab/data:/var/opt/gitlab"
    shm_size: "512m"
    depends_on:
      - ldap

  # NEXTCLOUD

  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    restart: unless-stopped
    ports:
      - 8081:80
    volumes:
      - ./cloud:/var/www/html
    environment:
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=admin
      - SQLITE_DATABASE=nextcloud
      - SQLITE_USER=nextcloud
      - SQLITE_PASSWORD=admin
    depends_on:
      - ldap

  # REDMINE

  redmine:
    image: redmine
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      REDMINE_DB_MYSQL: redmine_db
      REDMINE_DB_PASSWORD: redmine
      REDMINE_SECRET_KEY_BASE: supersecretkey
    depends_on:
      - ldap
      - redmine_db

  redmine_db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: redmine
      MYSQL_DATABASE: redmine
    depends_on:
      - ldap

volumes:
  ldap_data:
  ldap_config:
