version: "3.6"

services:
  # REVERSE PROXY

  nginx:
    image: "jc21/nginx-proxy-manager:latest"
    container_name: reverse-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "81:81"
    volumes:
      - ./proxy/data:/data
      - ./proxy/letsencrypt:/etc/letsencrypt
  # LDAP

  ldap:
    image: osixia/openldap
    environment:
      LDAP_ORGANISATION: "Meta"
      LDAP_ADMIN_PASSWORD: "admin"
    restart: always
    ports:
      - "389:389"
    volumes:
      - ./ldap/ldap_data:/var/lib/ldap
      - ./ldap/ldap_config:/etc/ldap/slapd.d

  phpldapadmin:
    image: osixia/phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: ldap
      PHPLDAPADMIN_HTTPS: "false"
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - ldap

  # GITLAB

  web-gitlab:
    image: "gitlab/gitlab-ee:latest"
    restart: unless-stopped
    hostname: "web-gitlab"
    ports:
      - "82:80"
      - "2443:443"
    volumes:
      - "./gitlab/config:/etc/gitlab"
      - "./gitlab/logs:/var/log/gitlab"
      - "./gitlab/data:/var/opt/gitlab"
    shm_size: "512m"
    depends_on:
      - ldap

  # NEXTCLOUD

  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    restart: unless-stopped
    ports:
      - 8081:80
    volumes:
      - ./cloud:/var/www/html
    environment:
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=admin
      - SQLITE_DATABASE=nextcloud
      - SQLITE_USER=nextcloud
      - SQLITE_PASSWORD=admin
    depends_on:
      - ldap

  # MOODLE
  mariadb:
    image: mariadb
    restart: unless-stopped
    volumes:
      - ./moodle/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=moodle
      - MYSQL_ROOT_USER=root
      - MYSQL_DATABASE=moodle
  moodle:
    image: bitnami/moodle:latest
    restart: unless-stopped
    ports:
      - 9080:8080
      - 9443:8443
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_USER=root
      - MOODLE_DATABASE_PASSWORD=moodle
      - MOODLE_DATABASE_NAME=moodle
      - PUID=998
      - PGID=100
    volumes:
      - ./moodle/moodle:/bitnami/moodle
      - ./moodle/moodleData:/bitnami/moodledata
    depends_on:
      - mariadb

  # VPN

  wg:
    image: ngoduykhanh/wireguard-ui:latest
    cap_add:
      - NET_ADMIN
    ports:
      - 5000:5000
      - 51820:51820
    environment:
      - WGUI_USERNAME=admin
      - WGUI_PASSWORD=admin
      - WGUI_DNS=192.168.2.1
      - WGUI_MANAGE_START=false
      - WGUI_MANAGE_RESTART=false
    logging:
      driver: json-file
      options:
        max-size: 50m
    volumes:
      - ./vpn/db:/app/db
      - ./vpn/wireguard:/etc/wireguard

  # REDMINE

  redmine:
    image: redmine
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      REDMINE_DB_MYSQL: redmine_db
      REDMINE_DB_PASSWORD: redmine
      REDMINE_SECRET_KEY_BASE: supersecretkey
    depends_on:
      - ldap
      - redmine_db

  redmine_db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: redmine
      MYSQL_DATABASE: redmine
    depends_on:
      - ldap
