version: "3.6"

services:
  web-gitlab:
    image: "gitlab/gitlab-ee:latest"
    restart: unless-stopped
    hostname: "web-gitlab"
    ports:
      - "82:80"
      - "2443:443"
    volumes:
      - "./gitlab/config:/etc/gitlab"
      - "./gitlab/logs:/var/log/gitlab"
      - "./gitlab/data:/var/opt/gitlab"
    shm_size: "512m"
    depends_on:
      - ldap

  ldap:
    image: osixia/openldap
    environment:
      LDAP_ORGANISATION: "Meta"
      LDAP_ADMIN_PASSWORD: "admin"
    ports:
      - "389:389"
    volumes:
      - ./ldap/ldap_data:/var/lib/ldap
      - ./ldap/ldap_config:/etc/ldap/slapd.d

  phpldapadmin:
    image: osixia/phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: ldap
      PHPLDAPADMIN_HTTPS: "false"
    ports:
      - "8080:80"
    depends_on:
      - ldap

  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    restart: unless-stopped
    ports:
      - 8081:80
    volumes:
      - ./cloud:/var/www/html
    environment:
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=admin
      - SQLITE_DATABASE=nextcloud
      - SQLITE_USER=nextcloud
      - SQLITE_PASSWORD=admin
      - LDAP_SERVER_HOST=ldap
      - LDAP_SERVER_PORT=389
      - LDAP_BASE=dc=example,dc=com # Replace with your LDAP base DN
      - LDAP_USER_FILTER=(&(objectclass=inetOrgPerson)(uid=%uid))
      - LDAP_USER_LOGIN_FILTER=(&(objectclass=inetOrgPerson)(uid=%uid))
      - LDAP_BIND_TYPE=login
      - LDAP_ADMIN_USERNAME=admin # LDAP bind DN
      - LDAP_ADMIN_PASSWORD=admin
    depends_on:
      - ldap

volumes:
  ldap_data:
  ldap_config:
