version: '3.7'

services:
  moodle_db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: moodle
      MYSQL_USER: moodle
      MYSQL_PASSWORD: moodle
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./moodle_data:/var/lib/mysql

  moodle:
    image: moodlehq/moodleapp:latest
    restart: always
    ports:
      - "8100:8100"
    depends_on:
      - moodle_db
    environment:
      MOODLE_DATABASE_TYPE: mysqli
      MOODLE_DATABASE_HOST: moodle_db
      MOODLE_DATABASE_NAME: moodle
      MOODLE_DATABASE_USER: moodle
      MOODLE_DATABASE_PASSWORD: moodle