version: '3.7'

services:
  ldap:
    image: osixia/openldap
    environment:
      LDAP_ORGANISATION: "Meta"
      LDAP_ADMIN_PASSWORD: "admin"
    ports:
      - "389:389"
    volumes:
      - ./ldap/ldap_data:/var/lib/ldap
      - ./ldap/ldap_config:/etc/ldap/slapd.d

  phpldapadmin:
    image: osixia/phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: ldap
      PHPLDAPADMIN_HTTPS: "false"
    ports:
      - "8080:80"
    depends_on:
      - ldap

  mariadb:
    image: docker.io/bitnami/mariadb:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_moodle
      - MARIADB_DATABASE=bitnami_moodle
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
    volumes:
      - 'mariadb_data:/bitnami/mariadb'

  moodle:
    image: docker.io/bitnami/moodle:latest
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_NAME=bitnami_moodle
      # Configure Moodle to use LDAP
      - MOODLE_AUTH='ldap'
      - MOODLE_LDAP_HOST='ldap'
      - MOODLE_LDAP_EXT_UID_FIELD='uid'
      - MOODLE_LDAP_CONTEXTS='dc=example,dc=org'  # Adjust this to match your LDAP setup
      - MOODLE_LDAP_USER_TYPE='posixAccount'  # Adjust as needed
      - MOODLE_LDAP_VERSION='3'  # Adjust as needed
      - MOODLE_LDAP_OPT_DN='cn=admin,dc=example,dc=org'  # Adjust this to match your LDAP admin DN
      - MOODLE_LDAP_OPT_PASSWORD='admin'  # Adjust this to match your LDAP admin password
      - MOODLE_LDAP_OPT_FOLLOWREFS='1'
      - MOODLE_LDAP_OPT_NETWORK_TIMEOUT='10'
      - MOODLE_LDAP_OPT_PROTOCOL_VERSION='3'
      - MOODLE_LDAP_OPT_REFERRALS='0'
      - MOODLE_LDAP_OPT_DEREF='0'
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'moodle_data:/bitnami/moodle'
      - 'moodledata_data:/bitnami/moodledata'
    depends_on:
      - mariadb
      - ldap  # Depend on the LDAP service

volumes:
  mariadb_data:
    driver: local
  moodle_data:
    driver: local
  moodledata_data:
    driver: local
  ldap_data:
    driver: local
  ldap_config:
    driver: local
