version: '3'

services:
  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./cloud:/var/www/html
    environment:
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=admin
      - SQLITE_DATABASE=nextcloud
      - SQLITE_USER=nextcloud
      - SQLITE_PASSWORD=admin

volumes:
  nextcloud:
